import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "p1",
    name: "Sea Salt Coconut Chips",
    category: "food",
    price: 6,
    basePrice: 6,
    unit: "bag",
    perishable: true,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p1.svg",
    seller: "Maya's Kitchen",
    sellerId: "mayas-kitchen",
    sellerAvatar: "/products/seller-maya-s-kitchen.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "compostable packaging",
    materialIndex: "Renewable Coconut Husk",
    replantingImpact: "1 coastal mangrove sapling",
    courierMilesPerItem: 3.5,
    description: "Sun-dried coconut chips, lightly salted, from small-batch island harvest.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 6, discountPct: 0 },
      { minQty: 3, pricePerUnit: 5.1, discountPct: 15 },
      { minQty: 5, pricePerUnit: 4.2, discountPct: 30 },
    ],
  },
  {
    id: "p2",
    name: "Wild Island Honey (12oz)",
    category: "food",
    price: 14,
    basePrice: 14,
    unit: "jar",
    perishable: false,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p2.svg",
    seller: "Tomas Apiary",
    sellerId: "tomas-apiary",
    sellerAvatar: "/products/seller-tomas-apiary.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "reusable glass jar",
    materialIndex: "Wild Forest Flora Nectar",
    replantingImpact: "2 native wildflower bio-corridors",
    courierMilesPerItem: 4.2,
    description: "Raw honey from wild hives, unfiltered and unheated.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 14, discountPct: 0 },
      { minQty: 3, pricePerUnit: 11.9, discountPct: 15 },
      { minQty: 5, pricePerUnit: 9.8, discountPct: 30 },
    ],
  },
  {
    id: "p3",
    name: "Turmeric-Ginger Spice Blend",
    category: "food",
    price: 8,
    basePrice: 8,
    unit: "pouch",
    perishable: false,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p3.svg",
    seller: "Nalini Spice House",
    sellerId: "nalini-spice-house",
    sellerAvatar: "/products/seller-nalini-spice-house.svg",
    atollHub: "Ridge Heights Atoll Hub",
    ecoTag: "recycled paper pouch",
    materialIndex: "Solar-Dried Organic Roots",
    replantingImpact: "1 ridge soil conservation plot",
    courierMilesPerItem: 5.1,
    description: "House spice blend grown and dried on the island's east ridge.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 8, discountPct: 0 },
      { minQty: 3, pricePerUnit: 6.8, discountPct: 15 },
      { minQty: 5, pricePerUnit: 5.6, discountPct: 30 },
    ],
  },
  {
    id: "p4",
    name: "Cold-Pressed Coconut Oil (16oz)",
    category: "wellness",
    price: 18,
    basePrice: 18,
    unit: "jar",
    perishable: false,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p4.svg",
    seller: "GreenRoot Co-op",
    sellerId: "greenroot-coop",
    sellerAvatar: "/products/seller-greenroot-co-op.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "zero plastic",
    materialIndex: "Organic Fallen Coconut Copra",
    replantingImpact: "2 coastal mangrove saplings",
    courierMilesPerItem: 3.8,
    description: "Multi-use virgin oil for cooking, skin, and hair care.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 18, discountPct: 0 },
      { minQty: 3, pricePerUnit: 15.3, discountPct: 15 },
      { minQty: 5, pricePerUnit: 12.6, discountPct: 30 },
    ],
  },
  {
    id: "p5",
    name: "Handwoven Palm Basket",
    category: "craft",
    price: 32,
    basePrice: 32,
    unit: "basket",
    perishable: false,
    consumable: false,
    bulkFriendly: false,
    bulkAvailable: false,
    image: "/products/p5.svg",
    seller: "Lani Weaves",
    sellerId: "lani-weaves",
    sellerAvatar: "/products/seller-lani-weaves.svg",
    atollHub: "South Shore Atoll Hub",
    ecoTag: "100% natural palm fiber",
    materialIndex: "Sustainably Pruned Palm Fronds",
    replantingImpact: "3 coastal mangrove saplings",
    courierMilesPerItem: 6.0,
    description: "Sturdy market basket woven using traditional island pattern.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 32, discountPct: 0 },
      { minQty: 3, pricePerUnit: 27.2, discountPct: 15 },
      { minQty: 5, pricePerUnit: 22.4, discountPct: 30 },
    ],
  },
  {
    id: "p6",
    name: "Seashell & Sea Glass Necklace",
    category: "craft",
    price: 24,
    basePrice: 24,
    unit: "piece",
    perishable: false,
    consumable: false,
    bulkFriendly: false,
    bulkAvailable: false,
    image: "/products/p6.svg",
    seller: "Coral Coast Crafts",
    sellerId: "coral-coast-crafts",
    sellerAvatar: "/products/seller-coral-coast-crafts.svg",
    atollHub: "South Shore Atoll Hub",
    ecoTag: "upcycled beach finds",
    materialIndex: "Upcycled Beach Glass & Shells",
    replantingImpact: "3 coral nursery plugs",
    courierMilesPerItem: 4.8,
    description: "Hand-strung pendant made with reclaimed ocean materials.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 24, discountPct: 0 },
      { minQty: 3, pricePerUnit: 20.4, discountPct: 15 },
      { minQty: 5, pricePerUnit: 16.8, discountPct: 30 },
    ],
  },
  {
    id: "p7",
    name: "Driftwood Wall Art",
    category: "craft",
    price: 45,
    basePrice: 45,
    unit: "piece",
    perishable: false,
    consumable: false,
    bulkFriendly: false,
    bulkAvailable: false,
    image: "/products/p7.svg",
    seller: "Coral Coast Crafts",
    sellerId: "coral-coast-crafts",
    sellerAvatar: "/products/seller-coral-coast-crafts.svg",
    atollHub: "South Shore Atoll Hub",
    ecoTag: "sustainably gathered wood",
    materialIndex: "100% Fallen Sea Driftwood",
    replantingImpact: "2 coastal mangrove saplings",
    courierMilesPerItem: 5.5,
    description: "One-of-a-kind wall hanging shaped by tides and finished by hand.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 45, discountPct: 0 },
      { minQty: 3, pricePerUnit: 38, discountPct: 15 },
      { minQty: 5, pricePerUnit: 32, discountPct: 30 },
    ],
  },
  {
    id: "p8",
    name: "Bamboo Utensil Set",
    category: "sustainable-goods",
    price: 12,
    basePrice: 12,
    unit: "set",
    perishable: false,
    consumable: false,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p8.svg",
    seller: "GreenRoot Co-op",
    sellerId: "greenroot-coop",
    sellerAvatar: "/products/seller-greenroot-co-op.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "reusable travel pouch",
    materialIndex: "Rapid-Renewable Wild Bamboo",
    replantingImpact: "1 bamboo grove sapling",
    courierMilesPerItem: 3.2,
    description: "Fork, spoon, knife, straw, and cleaning brush in travel wrap.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 12, discountPct: 0 },
      { minQty: 3, pricePerUnit: 10.2, discountPct: 15 },
      { minQty: 5, pricePerUnit: 8.4, discountPct: 30 },
    ],
  },
  {
    id: "p9",
    name: "Reef-Safe Sunscreen (4oz)",
    category: "wellness",
    price: 16,
    basePrice: 16,
    unit: "tin",
    perishable: false,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p9.svg",
    seller: "GreenRoot Co-op",
    sellerId: "greenroot-coop",
    sellerAvatar: "/products/seller-greenroot-co-op.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "non-nano zinc & tin container",
    materialIndex: "Biodegradable Marine Minerals",
    replantingImpact: "4 coral nursery fragments",
    courierMilesPerItem: 4.0,
    description: "Broad spectrum SPF 30 made with non-toxic marine minerals.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 16, discountPct: 0 },
      { minQty: 3, pricePerUnit: 13.6, discountPct: 15 },
      { minQty: 5, pricePerUnit: 11.2, discountPct: 30 },
    ],
  },
  {
    id: "p10",
    name: "Coconut Soap Bar (3-pack)",
    category: "wellness",
    price: 10,
    basePrice: 10,
    unit: "pack",
    perishable: false,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p10.svg",
    seller: "Maya's Kitchen",
    sellerId: "mayas-kitchen",
    sellerAvatar: "/products/seller-maya-s-kitchen.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "biodegradable wrapper",
    materialIndex: "Solar Cold-Process Coconut Oil",
    replantingImpact: "1 coastal mangrove sapling",
    courierMilesPerItem: 3.5,
    description: "Moisturizing cold-process soap bars enriched with island botanicals.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 10, discountPct: 0 },
      { minQty: 3, pricePerUnit: 8.5, discountPct: 15 },
      { minQty: 5, pricePerUnit: 7.0, discountPct: 30 },
    ],
  },
  {
    id: "p11",
    name: "Artisan Sea Salt Grinder",
    category: "food",
    price: 11,
    basePrice: 11,
    unit: "grinder",
    perishable: false,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p11.svg",
    seller: "Maya's Kitchen",
    sellerId: "mayas-kitchen",
    sellerAvatar: "/products/seller-maya-s-kitchen.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "refillable glass grinder",
    materialIndex: "Solar-Evaporated Ocean Salt",
    replantingImpact: "1 coastal mangrove sapling",
    courierMilesPerItem: 3.0,
    description: "Coarse sun-evaporated reef salt harvested from clean tidal pools.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 11, discountPct: 0 },
      { minQty: 3, pricePerUnit: 9.35, discountPct: 15 },
      { minQty: 5, pricePerUnit: 7.7, discountPct: 30 },
    ],
  },
  {
    id: "p12",
    name: "Organic Vanilla Pods (5-pack)",
    category: "food",
    price: 22,
    basePrice: 22,
    unit: "pack",
    perishable: false,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p12.svg",
    seller: "Nalini Spice House",
    sellerId: "nalini-spice-house",
    sellerAvatar: "/products/seller-nalini-spice-house.svg",
    atollHub: "Ridge Heights Atoll Hub",
    ecoTag: "glass test tube",
    materialIndex: "Shade-Grown Orchid Vanilla",
    replantingImpact: "2 rainforest canopy trees",
    courierMilesPerItem: 4.5,
    description: "Grade-A sun-cured bourbon vanilla beans with rich floral aroma.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 22, discountPct: 0 },
      { minQty: 3, pricePerUnit: 18.7, discountPct: 15 },
      { minQty: 5, pricePerUnit: 15.4, discountPct: 30 },
    ],
  },
  {
    id: "p13",
    name: "Island Passionfruit Jam (8oz)",
    category: "food",
    price: 9,
    basePrice: 9,
    unit: "jar",
    perishable: true,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p13.svg",
    seller: "Maya's Kitchen",
    sellerId: "mayas-kitchen",
    sellerAvatar: "/products/seller-maya-s-kitchen.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "recycled lid",
    materialIndex: "Wild Harvested Passionfruit",
    replantingImpact: "1 fruit tree nursery sapling",
    courierMilesPerItem: 3.2,
    description: "Small-batch preserves made with fresh island pulp and wild honey.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 9, discountPct: 0 },
      { minQty: 3, pricePerUnit: 7.65, discountPct: 15 },
      { minQty: 5, pricePerUnit: 6.3, discountPct: 30 },
    ],
  },
  {
    id: "p14",
    name: "Botanical Hair & Scalp Tonic",
    category: "wellness",
    price: 20,
    basePrice: 20,
    unit: "bottle",
    perishable: false,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p14.svg",
    seller: "GreenRoot Co-op",
    sellerId: "greenroot-coop",
    sellerAvatar: "/products/seller-greenroot-co-op.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "amber glass dropper",
    materialIndex: "Cold Infused Hibiscus & Neem",
    replantingImpact: "2 coastal mangrove saplings",
    courierMilesPerItem: 3.9,
    description: "Nutrient-rich oil blend infused with island hibiscus flowers.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 20, discountPct: 0 },
      { minQty: 3, pricePerUnit: 17.0, discountPct: 15 },
      { minQty: 5, pricePerUnit: 14.0, discountPct: 30 },
    ],
  },
  {
    id: "p15",
    name: "Volcanic Ash Face Mask (4oz)",
    category: "wellness",
    price: 15,
    basePrice: 15,
    unit: "jar",
    perishable: false,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p15.svg",
    seller: "GreenRoot Co-op",
    sellerId: "greenroot-coop",
    sellerAvatar: "/products/seller-greenroot-co-op.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "aluminized tin",
    materialIndex: "Purified Mineral Ash",
    replantingImpact: "1 coral reef protection fund unit",
    courierMilesPerItem: 3.6,
    description: "Detoxifying clay mask harvested from natural mineral springs.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 15, discountPct: 0 },
      { minQty: 3, pricePerUnit: 12.75, discountPct: 15 },
      { minQty: 5, pricePerUnit: 10.5, discountPct: 30 },
    ],
  },
  {
    id: "p16",
    name: "Aloe Vera Hydrating Mist",
    category: "wellness",
    price: 13,
    basePrice: 13,
    unit: "spray",
    perishable: false,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p16.svg",
    seller: "GreenRoot Co-op",
    sellerId: "greenroot-coop",
    sellerAvatar: "/products/seller-greenroot-co-op.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "recycled aluminum bottle",
    materialIndex: "Organic Fresh Aloe Juice",
    replantingImpact: "2 coastal mangrove saplings",
    courierMilesPerItem: 3.4,
    description: "Refreshing after-sun facial spray with wild aloe and cucumber hydrosol.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 13, discountPct: 0 },
      { minQty: 3, pricePerUnit: 11.05, discountPct: 15 },
      { minQty: 5, pricePerUnit: 9.1, discountPct: 30 },
    ],
  },
  {
    id: "p17",
    name: "Handwoven Pandanus Tote Bag",
    category: "craft",
    price: 38,
    basePrice: 38,
    unit: "bag",
    perishable: false,
    consumable: false,
    bulkFriendly: false,
    bulkAvailable: false,
    image: "/products/p17.svg",
    seller: "Lani Weaves",
    sellerId: "lani-weaves",
    sellerAvatar: "/products/seller-lani-weaves.svg",
    atollHub: "South Shore Atoll Hub",
    ecoTag: "biodegradable fibers",
    materialIndex: "Sun-Cured Pandanus Leaves",
    replantingImpact: "4 coastal mangrove saplings",
    courierMilesPerItem: 6.2,
    description: "Durable beach tote with reinforced coconut wood handles.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 38, discountPct: 0 },
      { minQty: 3, pricePerUnit: 32.3, discountPct: 15 },
      { minQty: 5, pricePerUnit: 26.6, discountPct: 30 },
    ],
  },
  {
    id: "p18",
    name: "Carved Coconut Shell Bowl",
    category: "craft",
    price: 19,
    basePrice: 19,
    unit: "bowl",
    perishable: false,
    consumable: false,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p18.svg",
    seller: "Coral Coast Crafts",
    sellerId: "coral-coast-crafts",
    sellerAvatar: "/products/seller-coral-coast-crafts.svg",
    atollHub: "South Shore Atoll Hub",
    ecoTag: "food-safe coconut wax finish",
    materialIndex: "Upcycled Coconut Shell",
    replantingImpact: "2 coastal mangrove saplings",
    courierMilesPerItem: 4.6,
    description: "Smooth hand-sanded bowl polished with organic virgin coconut oil.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 19, discountPct: 0 },
      { minQty: 3, pricePerUnit: 16.15, discountPct: 15 },
      { minQty: 5, pricePerUnit: 13.3, discountPct: 30 },
    ],
  },
  {
    id: "p19",
    name: "Hand-Carved Wooden Spoon",
    category: "craft",
    price: 15,
    basePrice: 15,
    unit: "spoon",
    perishable: false,
    consumable: false,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p19.svg",
    seller: "Coral Coast Crafts",
    sellerId: "coral-coast-crafts",
    sellerAvatar: "/products/seller-coral-coast-crafts.svg",
    atollHub: "South Shore Atoll Hub",
    ecoTag: " beeswax seal",
    materialIndex: "Reclaimed Island Teak",
    replantingImpact: "2 native hardwood saplings",
    courierMilesPerItem: 4.4,
    description: "Sculpted cooking spoon shaped from fallen island timber.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 15, discountPct: 0 },
      { minQty: 3, pricePerUnit: 12.75, discountPct: 15 },
      { minQty: 5, pricePerUnit: 10.5, discountPct: 30 },
    ],
  },
  {
    id: "p20",
    name: "Sea Glass Wind Chime",
    category: "craft",
    price: 29,
    basePrice: 29,
    unit: "chime",
    perishable: false,
    consumable: false,
    bulkFriendly: false,
    bulkAvailable: false,
    image: "/products/p20.svg",
    seller: "Coral Coast Crafts",
    sellerId: "coral-coast-crafts",
    sellerAvatar: "/products/seller-coral-coast-crafts.svg",
    atollHub: "South Shore Atoll Hub",
    ecoTag: "reclaimed ocean glass",
    materialIndex: "Frosty Wave-Tumbled Glass",
    replantingImpact: "3 coral nursery plugs",
    courierMilesPerItem: 5.2,
    description: "Soothing musical chime strung on hemp cord with ocean-tumbled glass pieces.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 29, discountPct: 0 },
      { minQty: 3, pricePerUnit: 24.65, discountPct: 15 },
      { minQty: 5, pricePerUnit: 20.3, discountPct: 30 },
    ],
  },
  {
    id: "p21",
    name: "Reusable Organic Cotton Tote",
    category: "sustainable-goods",
    price: 14,
    basePrice: 14,
    unit: "bag",
    perishable: false,
    consumable: false,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p21.svg",
    seller: "GreenRoot Co-op",
    sellerId: "greenroot-coop",
    sellerAvatar: "/products/seller-greenroot-co-op.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "GOTS organic cotton",
    materialIndex: "Unbleached Organic Cotton Canvas",
    replantingImpact: "1 mangrove sapling",
    courierMilesPerItem: 3.1,
    description: "Heavyweight tote printed with eco water-based island ink.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 14, discountPct: 0 },
      { minQty: 3, pricePerUnit: 11.9, discountPct: 15 },
      { minQty: 5, pricePerUnit: 9.8, discountPct: 30 },
    ],
  },
  {
    id: "p22",
    name: "Stainless Steel Insulated Bottle",
    category: "sustainable-goods",
    price: 25,
    basePrice: 25,
    unit: "bottle",
    perishable: false,
    consumable: false,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p22.svg",
    seller: "GreenRoot Co-op",
    sellerId: "greenroot-coop",
    sellerAvatar: "/products/seller-greenroot-co-op.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "lifetime durability",
    materialIndex: "18/8 Food Grade Recycled Steel",
    replantingImpact: "2 ocean plastic cleanup units",
    courierMilesPerItem: 3.6,
    description: "Keeps drinks cold for 24 hours with leakproof bamboo cap.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 25, discountPct: 0 },
      { minQty: 3, pricePerUnit: 21.25, discountPct: 15 },
      { minQty: 5, pricePerUnit: 17.5, discountPct: 30 },
    ],
  },
  {
    id: "p23",
    name: "Beeswax Food Wraps (3-pack)",
    category: "sustainable-goods",
    price: 16,
    basePrice: 16,
    unit: "pack",
    perishable: false,
    consumable: false,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p23.svg",
    seller: "Tomas Apiary",
    sellerId: "tomas-apiary",
    sellerAvatar: "/products/seller-tomas-apiary.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "plastic-wrap alternative",
    materialIndex: "Wild Beeswax & Organic Cotton",
    replantingImpact: "2 wildflower plots",
    courierMilesPerItem: 3.3,
    description: "Reusable washable wraps for produce and bowls.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 16, discountPct: 0 },
      { minQty: 3, pricePerUnit: 13.6, discountPct: 15 },
      { minQty: 5, pricePerUnit: 11.2, discountPct: 30 },
    ],
  },
  {
    id: "p24",
    name: "Recycled Paper Journal",
    category: "sustainable-goods",
    price: 18,
    basePrice: 18,
    unit: "journal",
    perishable: false,
    consumable: false,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p24.svg",
    seller: "Lani Weaves",
    sellerId: "lani-weaves",
    sellerAvatar: "/products/seller-lani-weaves.svg",
    atollHub: "South Shore Atoll Hub",
    ecoTag: "100% post-consumer paper",
    materialIndex: "Recycled Cotton & Plant Fiber",
    replantingImpact: "1 tree nursery seedling",
    courierMilesPerItem: 4.1,
    description: "Hardcover notebook bound with hand-dyed cotton cord.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 18, discountPct: 0 },
      { minQty: 3, pricePerUnit: 15.3, discountPct: 15 },
      { minQty: 5, pricePerUnit: 12.6, discountPct: 30 },
    ],
  },
  {
    id: "p25",
    name: "Solar-Dried Mango Slices",
    category: "food",
    price: 7,
    basePrice: 7,
    unit: "pouch",
    perishable: true,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p25.svg",
    seller: "Maya's Kitchen",
    sellerId: "mayas-kitchen",
    sellerAvatar: "/products/seller-maya-s-kitchen.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "no added sugar",
    materialIndex: "Tree-Ripened Organic Mango",
    replantingImpact: "1 orchard tree sapling",
    courierMilesPerItem: 3.1,
    description: "Chewy solar-dried mango strips packed with natural island sweetness.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 7, discountPct: 0 },
      { minQty: 3, pricePerUnit: 5.95, discountPct: 15 },
      { minQty: 5, pricePerUnit: 4.9, discountPct: 30 },
    ],
  },
  {
    id: "p26",
    name: "Lemongrass Essential Oil (15ml)",
    category: "wellness",
    price: 17,
    basePrice: 17,
    unit: "bottle",
    perishable: false,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p26.svg",
    seller: "Nalini Spice House",
    sellerId: "nalini-spice-house",
    sellerAvatar: "/products/seller-nalini-spice-house.svg",
    atollHub: "Ridge Heights Atoll Hub",
    ecoTag: "steam-distilled",
    materialIndex: "Wild Harvested Lemongrass",
    replantingImpact: "2 soil restoration plots",
    courierMilesPerItem: 4.7,
    description: "Pure steam-distilled essential oil for aromatherapy and natural bug repellant.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 17, discountPct: 0 },
      { minQty: 3, pricePerUnit: 14.45, discountPct: 15 },
      { minQty: 5, pricePerUnit: 11.9, discountPct: 30 },
    ],
  },
  {
    id: "p27",
    name: "Woven Pandanus Placemat Set",
    category: "craft",
    price: 28,
    basePrice: 28,
    unit: "set",
    perishable: false,
    consumable: false,
    bulkFriendly: false,
    bulkAvailable: false,
    image: "/products/p27.svg",
    seller: "Lani Weaves",
    sellerId: "lani-weaves",
    sellerAvatar: "/products/seller-lani-weaves.svg",
    atollHub: "South Shore Atoll Hub",
    ecoTag: "hand-dyed botanicals",
    materialIndex: "Natural Pandanus Weave",
    replantingImpact: "3 mangrove saplings",
    courierMilesPerItem: 5.8,
    description: "Set of 4 dining placemats woven with natural coconut fiber borders.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 28, discountPct: 0 },
      { minQty: 3, pricePerUnit: 23.8, discountPct: 15 },
      { minQty: 5, pricePerUnit: 19.6, discountPct: 30 },
    ],
  },
  {
    id: "p28",
    name: "Coconut Sugar (16oz)",
    category: "food",
    price: 10,
    basePrice: 10,
    unit: "pouch",
    perishable: false,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p28.svg",
    seller: "Maya's Kitchen",
    sellerId: "mayas-kitchen",
    sellerAvatar: "/products/seller-maya-s-kitchen.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "low-glycemic sweetener",
    materialIndex: "Unrefined Coconut Blossom Sap",
    replantingImpact: "1 palm grove protection unit",
    courierMilesPerItem: 3.3,
    description: "Low-glycemic unrefined sweetener cooked down over open coconut husk fires.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 10, discountPct: 0 },
      { minQty: 3, pricePerUnit: 8.5, discountPct: 15 },
      { minQty: 5, pricePerUnit: 7.0, discountPct: 30 },
    ],
  },
  {
    id: "p29",
    name: "Herbal Sea Salt Bath Soak",
    category: "wellness",
    price: 14,
    basePrice: 14,
    unit: "jar",
    perishable: false,
    consumable: true,
    bulkFriendly: true,
    bulkAvailable: true,
    image: "/products/p29.svg",
    seller: "GreenRoot Co-op",
    sellerId: "greenroot-coop",
    sellerAvatar: "/products/seller-greenroot-co-op.svg",
    atollHub: "North Atoll Co-op Hub",
    ecoTag: "magnesium-rich",
    materialIndex: "Ocean Salt & Dried Botanicals",
    replantingImpact: "2 coral reef nursery plugs",
    courierMilesPerItem: 3.7,
    description: "Soothing bath salts infused with island lavender and eucalyptus oil.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 14, discountPct: 0 },
      { minQty: 3, pricePerUnit: 11.9, discountPct: 15 },
      { minQty: 5, pricePerUnit: 9.8, discountPct: 30 },
    ],
  },
  {
    id: "p30",
    name: "Upcycled Sailcloth Storage Bin",
    category: "sustainable-goods",
    price: 36,
    basePrice: 36,
    unit: "bin",
    perishable: false,
    consumable: false,
    bulkFriendly: false,
    bulkAvailable: false,
    image: "/products/p30.svg",
    seller: "Coral Coast Crafts",
    sellerId: "coral-coast-crafts",
    sellerAvatar: "/products/seller-coral-coast-crafts.svg",
    atollHub: "South Shore Atoll Hub",
    ecoTag: "reclaimed sailboat canvas",
    materialIndex: "100% Upcycled Marine Sailcloth",
    replantingImpact: "3 ocean debris cleanup units",
    courierMilesPerItem: 5.9,
    description: "Water-resistant storage bin stitched from retired island sailboat sails.",
    tierPricing: [
      { minQty: 1, pricePerUnit: 36, discountPct: 0 },
      { minQty: 3, pricePerUnit: 30.6, discountPct: 15 },
      { minQty: 5, pricePerUnit: 25.2, discountPct: 30 },
    ],
  },
];
