/**
 * Sample catalog — demo fixture only. In production the frontend passes the real
 * `products` array in the request body; the API never depends on this file.
 */
import type { Product } from "./types";

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "p-coffee-500",
    name: "House Blend Coffee, 500g",
    category: "pantry",
    price: 12,
    unit: "bag",
    packaging: "minimal",
    bulkAvailable: true,
    consumable: true,
    sizeTier: "medium",
  },
  {
    id: "p-coffee-pods-10",
    name: "Single-Serve Coffee Pods, 10-pack",
    category: "pantry",
    price: 8,
    unit: "pack",
    unitsPerPack: 10,
    packaging: "heavy",
    consumable: true,
    sizeTier: "small",
  },
  {
    id: "p-dish-soap-1l",
    name: "Concentrated Dish Soap, 1L Refill",
    category: "home-care",
    price: 9,
    unit: "pouch",
    packaging: "minimal",
    bulkAvailable: true,
    consumable: true,
    sizeTier: "large",
  },
  {
    id: "p-dish-soap-glass",
    name: "Dish Soap, 400ml Glass Bottle",
    category: "home-care",
    price: 7,
    unit: "bottle",
    packaging: "standard",
    consumable: true,
    sizeTier: "small",
  },
  {
    id: "p-gift-candle",
    name: "Hand-Poured Soy Candle, Gift Boxed",
    category: "gifting",
    price: 28,
    unit: "box",
    packaging: "standard",
    consumable: false,
    sizeTier: "small",
  },
  {
    id: "p-tea-sampler",
    name: "Loose-Leaf Tea Sampler, Gift Tin",
    category: "gifting",
    price: 22,
    unit: "tin",
    packaging: "standard",
    consumable: false,
    sizeTier: "small",
  },
  {
    id: "p-paper-towel-12",
    name: "Recycled Paper Towels, 12 rolls",
    category: "home-care",
    price: 18,
    unit: "case",
    unitsPerPack: 12,
    packaging: "standard",
    bulkAvailable: true,
    consumable: true,
    sizeTier: "large",
  },
  {
    id: "p-water-bottle",
    name: "Insulated Steel Water Bottle, 750ml",
    category: "accessories",
    price: 25,
    unit: "bottle",
    packaging: "minimal",
    consumable: false,
    sizeTier: "medium",
  },
];
